global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'volcanion-tracking'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']
        labels:
          service: 'volcanion-tracking-api'
          environment: 'development'
